name: HTML Website CI

on:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Check HTML file
        run: |
          echo "Checking index.html..."
          ls -l
          cat index.html

      - name: Test HTML file
        run: |
          test -f index.html
          echo "index.html exists successfully!"
